server:
  port: 80
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    register-with-eureka: true #表示不向注册中心注册自己
    fetch-registry: true #false表示自己就是注册中心
    #单机7001就是自己
    service-url:
      defaultZone: http://localhost:7001/eureka/