server:
  port: 9001
  servlet:
    context-path: /system


spring:
  application:
    name: system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.2.135:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hao123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.finalhao.springcloud.entities #所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true #表示不向注册中心注册自己
    fetch-registry: true #false表示自己就是注册中心
    #单机7001就是自己
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: system9001
    prefer-ip-address: true #访问路径可以显示ip