spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.2.135:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hao123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.finalhao.springcloud.entities #所有Entity别名类所在包
logging:
  level:
    com.finalhao.server.dao: trace