server:
  port: 9001
  servlet:
    context-path: /system
spring:
  application:
    name: system
eureka:
  client:
    register-with-eureka: true #表示不向注册中心注册自己
    fetch-registry: true #false表示自己就是注册中心
    #单机7001就是自己
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: system9001
    prefer-ip-address: true #访问路径可以显示ip

