server:
  port: 9999
spring:
  redis:
    database: 0
    host: 192.168.2.135
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0

